// <auto-generated />
using CRD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRD.Migrations.usuario_mensagem
{
    [DbContext(typeof(Usuario_mensagemContext))]
    partial class usuario_mensagemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("CRD.Models.Usuario_mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdMensagem")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("MensagemLida")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("usuario_mensagem");
                });
#pragma warning restore 612, 618
        }
    }
}
